import js from "@eslint/js";
import tseslint from "@typescript-eslint/eslint-plugin";
import tsparser from "@typescript-eslint/parser";

export default [
  js.configs.recommended,
  {
    ignores: ["dist/**", "node_modules/**", "venv/**", "venv_kraken/**", "**/*.js", "scripts/**"],
  },
  {
    files: ["**/*.ts", "**/*.tsx"],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
        jsx: "react-jsx",
      },
      globals: {
        // Node.js
        process: "readonly",
        global: "readonly",
        console: "readonly",
        Buffer: "readonly",
        require: "readonly",
        module: "readonly",
        exports: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        globalThis: "readonly",
        setImmediate: "readonly",
        clearImmediate: "readonly",
        // Browser & DOM
        window: "readonly",
        document: "readonly",
        fetch: "readonly",
        FormData: "readonly",
        Blob: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        Request: "readonly",
        Response: "readonly",
        RequestInit: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        setInterval: "readonly",
        setTimeout: "readonly",
        clearInterval: "readonly",
        clearTimeout: "readonly",
        PerformanceObserver: "readonly",
        MutationObserver: "readonly",
        ResizeObserver: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        alert: "readonly",
        atob: "readonly",
        btoa: "readonly",
        WebSocket: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        Notification: "readonly",
        AudioContext: "readonly",
        AudioBuffer: "readonly",
        Image: "readonly",
        ImageBitmap: "readonly",
        createImageBitmap: "readonly",
        File: "readonly",
        FileList: "readonly",
        FileReader: "readonly",
        React: "readonly",
        HTMLElement: "readonly",
        HTMLDivElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLCanvasElement: "readonly",
        HTMLImageElement: "readonly",
        HTMLVideoElement: "readonly",
        HTMLTextAreaElement: "readonly",
        CanvasRenderingContext2D: "readonly",
        MouseEvent: "readonly",
        KeyboardEvent: "readonly",
        NodeJS: "readonly",
        Express: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        Window: "readonly",
      },
    },
    plugins: {
      "@typescript-eslint": tseslint,
    },
    rules: {
      ...tseslint.configs.recommended.rules,
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/consistent-type-imports": "off",
      "no-console": "off",
      "no-var": "off",
      "no-empty": ["error", { allowEmptyCatch: true }],
      "@typescript-eslint/ban-ts-comment": "off",
      "no-useless-assignment": "off",
      "no-useless-escape": "off",
      "no-unused-expressions": "off",
      "@typescript-eslint/no-unused-expressions": "off",
    },
  },
];